### ISSUE TITLE
Requesting to add the catalog

### ISSUE THREAD

**Issue by Sudhakarms2604** [sudhakarm2604/Skillupdevelopment#13]
Dear Sudhakar M

It would be great if we add the catalog feature in the admin command center, kindly please add this feature

**Comment by sudhakarm2604** [comment]
Dear sudhakar, 

Thanks for suggestion for the catalog feature , i will let you know once it is done

**Comment by sudhakarm2604** [comment]
Hi sudhakar, 

we have fixed the issue in our product,
